version: '3'
      services:
              web:
                      image: flask2025
                      build: .
                      env_file:
                              - .env
                      ports:
                              - "8887:8887"
                      volumes:
                              - ./instance:/instance
                      restart: unless-stopped
