version: '3'
<<<<<<< HEAD
      services:
              web:
                      image: flask2025
                      build: .
                      env_file:
                              - .env
                      ports:
                              - "8887:8887"
                      volumes:
                              - ./instance:/instance
                      restart: unless-stopped
=======
services:
        web:
                image: flask_2025
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8887:8887"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
>>>>>>> e07a0d7f4eb9ea6322077a2b9c01a22208f91110
